CXX = clang++
CXXFLAGS = -std=c++1y -stdlib=libc++
LDFLAGS = -std=c++1y -stdlib=libc++ -lc++abi -lpthread
TESTOBJS=png.o rgbapixel.o skipList.cpp skipNode.cpp skipList_given.cpp
include Makefile.proxy
